import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F9F9F9]`}
      >
        <img src="/assets/bg-image.jpg" alt="bg" className="fixed max-md:h-screen md:top-1/2 md:left-1/2 md:translate-x-[-50%] md:translate-y-[-50%] z-[-1] object-cover" />
        {children}
      </body>
    </html>
  );
}
